[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
random-number = "0.1.8"
csv = "1.2.1"
serde = {version = "1.0.160", features = ["derive"]}
rand = "0.8.5"
